### ISSUE TITLE
MGARD does not build with AppleClang

### ISSUE THREAD

**Issue by lindstro** [CODARcode/MGARD#228]
As noted in #189, MGARD does not build with AppleClang 14.0.3.14030022:
```
tests/src/test_compressors.cpp:128:76: error: cannot initialize a parameter of type 'long *' with an lvalue of type 'std::int64_t *const' (aka 'long long *const')
  mgard::decompress_memory_huffman(compressed.data.get(), compressed.size, dst,
                                                                           ^~~
include/compressors.hpp:33:74: note: passing argument to parameter 'dst' here
                               const std::size_t srcLen, long int *const dst,
                                                                         ^
tests/src/test_compressors.cpp:199:40: error: cannot initialize a parameter of type 'long *' with an lvalue of type 'std::int64_t *const' (aka 'long long *const')
        mgard::compress_memory_huffman(quantized_, ndof);
                                       ^~~~~~~~~~
include/compressors.hpp:23:69: note: passing argument to parameter 'src' here
MemoryBuffer<unsigned char> compress_memory_huffman(long int *const src,
```

**Comment by Jeff-Hadley** [comment]
Having the same issue. Does not build with AppleClang 15.0.0.15000100. 
![image](https://github.com/CODARcode/MGARD/assets/84529088/2096bcaa-a6e2-4631-8959-e93dcb4ccd22)
